### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods) 

### ISSUE THREAD

**Issue by RizanPSTU** [Meherdeep/agora-flutter-broadcast#1]
I get this error when try to go live 

Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

**Comment by Meherdeep** [comment]
@RizanPSTU

What version of Android are you running?

**Comment by RizanPSTU** [comment]
Android 9

**Comment by Meherdeep** [comment]
Here's what you can do:

1. Try running `flutter clean` and then try re-running the code.
2. Also, go through the setup page mentioned over [here ](https://pub.dev/packages/permission_handler). 
The package is developed for the latest android versions and it should work perfectly with Android X.

**Comment by RizanPSTU** [comment]
Did everything that you mentioned.

**Comment by Meherdeep** [comment]
@RizanPSTU 

Did that solve your query?

**Comment by Meherdeep** [comment]
I have updated the permission_handler package as the previous version was deprecated. 

You can pull the recent changes and it should work for you.
